spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/sksaude
    username: sksaude
    password: Luiz1992@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect