spring:
  datasource:
    url: jdbc:postgresql://db-postgresql-nyc3-05932-do-user-17893251-0.h.db.ondigitalocean.com:25060/sksaude
    username: doadmin
    password: AVNS_FMkvA0hJPwrz_06ZPGp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081