spring:
  datasource:
    url: jdbc:postgresql://10.120.162.195:5432/sksaude
    username: sksaude
    password: sksaude123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect